insert into CONFERENCE (ID ,CONFERENCE_NAME ) values (1,'회의실1')
insert into CONFERENCE (ID ,CONFERENCE_NAME ) values (2,'회의실2')
insert into CONFERENCE (ID ,CONFERENCE_NAME ) values (3,'회의실3')
insert into CONFERENCE (ID ,CONFERENCE_NAME ) values (4,'회의실4')
insert into CONFERENCE (ID ,CONFERENCE_NAME ) values (5,'회의실5')

insert into RESERVATION (ID,RESERVATION_NAME,REGIST_NAME,REGIST_DT,REPETITIONS_OF_NUM,VERSION ) values (1,'회의1','RAN',NOW(),1,0)
insert into RESERVATION (ID,RESERVATION_NAME,REGIST_NAME,REGIST_DT,REPETITIONS_OF_NUM,VERSION ) values (2,'회의2','LIM',NOW(),2,0)


insert into RESERVATED_DATE (ID,RESERVATION_DATE,VERSION ) values (1,'2019-12-25',0)
insert into RESERVATED_DATE (ID,RESERVATION_DATE,VERSION ) values (2,'2018-12-27',0)
insert into RESERVATED_DATE (ID,RESERVATION_DATE,VERSION ) values (3,'2018-12-28',0)

insert into RESERVATION_DETAIL (CONFERENCE_ID,RESERVATION_ID,RESERVATED_DATE_ID,START_TIME,END_TIME,VERSION ) values (1,1,1,'08:00','14:00',0)
insert into RESERVATION_DETAIL (CONFERENCE_ID,RESERVATION_ID,RESERVATED_DATE_ID,START_TIME,END_TIME,VERSION ) values (1,1,2,'14:00','18:00',0)
insert into RESERVATION_DETAIL (CONFERENCE_ID,RESERVATION_ID,RESERVATED_DATE_ID,START_TIME,END_TIME,VERSION) values (2,2,2,'08:00','14:00',0)
insert into RESERVATION_DETAIL (CONFERENCE_ID,RESERVATION_ID,RESERVATED_DATE_ID,START_TIME,END_TIME,VERSION ) values (2,2,3,'08:00','14:00',0)
